name: Testsss
env:
  MYVAR: "THis is value of my var"
  PTESTVERSION_GA: ${{secrets.PTESTVERSION_GA}}
on: [push]
jobs:
  Name_of_job_can_use_through_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code, Clone repo
        uses: actions/checkout@v3

      - name: Setu p Python3.8 name
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: IInstall dependencies
        run: pip install tox
        env:
          PTESTVERSION: '6.2.5'

      - run: echo "$MYVAR - MYVAR tuts "
      - run: echo "$PTESTVERSION_GA - PTESTVERSION_GA tuts "
      - run: echo "$PTESTVERSION - PTESTVERSION tuts "

      - name: Ruun py38 tets
        run: tox -e py38




#      - name: Run from workflow_dispatch
#        if: github.event_name == 'workflow_dispatch'
#        run: |
 #         echo "ered by a ${{ github.event.inputs.rebuild_branch }} erebuild_brancht."


