name: CI
on:
  workflow_dispatch:
    inputs:
      rebuild_image:
        description: 'choose branch master or dev,
                      and print true if need to rebuidl docker image.'
        required: False
        default: False
        type: boolean

  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  test_job:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code, Clone repo
        uses: actions/checkout@v3

      - run: echo "${{ github.event.inputs.rebuild_image }} "

      - run: echo "1 stri trye "
        if:  ${{ github.event.inputs.rebuild_image == 'true' }}

      - run: echo "2 bool Trye "
        if: ${{ github.event.inputs.rebuild_image == True }}

      - run: echo "3 bool trye "
        if: ${{ github.event.inputs.rebuild_image == true }}

      - run: echo "4 stri Trye "
        if: ${{ github.event.inputs.rebuild_image == 'True' }}

      - run: echo "${{ github.ref}} tuts $GITHUB_REF tuts "

      - run: echo "${{ github.base_ref}} tuts base ref tuts "
      - run: echo "${{ github.event_name}} event_nsmae ref tuts "

      - run: echo "111 iffff works "
        if: github.event_name == 'push'
  deploy_job:
    needs: test_job
    if: |
      always() &&
      ((needs.test_job.result == 'success' && github.event_name == 'push')  ||
      (needs.test_job.result == 'skipped' && github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code, Clone repo
        uses: actions/checkout@v3

      - run: echo "${{ needs.test_job.result }}"
      - run: echo "$needs.test_job.result"
      - run: echo $needs.test_job.result
      - run: echo ${{ needs.test_job.result }}
      - run: echo needs.test_job.result

      - run: echo "${{ github.ref}} tuts $GITHUB_REF tuts "
      - run: echo "${{ github.base_ref}} tuts base ref tuts "
      - run: echo "${{ github.event_name}} event_nsmae ref tuts "

      - run: echo "111 ifffffffff "
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - run: echo "222 ifffffffff "
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild_branch2 == 'true'

