name: Connect ssh
on:
  push:
jobs:
  Name_of_job_can_use_through_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" >  ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          ssh-keyscan -H dsc-uat-plumber01.productmadness.com > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_DEV_HOST: ${{ secrets.SSH_DEV_HOST }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Create dir0
        run: echo ${{ github.workspace }}/../private.key

      - name: Create dir00
        run: echo "${{ github.workspace }}/../private.key"

      - name: Create dir000
        run: echo "$SSH_KEY_PATH"

      - name: List files in the repository1
        run: |
          ls ${{ github.workspace }}/../../..

      - name: List files in the repository2
        run: |
          ls ${{ github.workspace }}/../../../..

      - name: List files in the repository3
        run: |
          ls ${{ github.workspace }}/../../../../..

      - name: Create dir
        run: ssh -i ~/.ssh/private.key kdouban@dsc-uat-plumber01.productmadness.com mkdir ~/tets