name: Connect ssh
on:
  push:
jobs:
  Name_of_job_can_use_through_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code, Clone repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host dev_host
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Stop the server
        #run: ssh dev_host 'sh ~/tetsss4/scripttest.sh'
        # run: ssh  'mkdir ~/tetsss5'
        #run: ssh -i ~/.ssh/private.key kdouban@dsc-uat-plumber01.productmadness.com 'mkdir ~/tetsss5'
        run: |
          ls .
          rsync -e 'ssh -i ~/.ssh/private.key' ${{ github.workspace }}/firstfile.py kdouban@dsc-uat-plumber01.productmadness.com:~/tetsss4/rs

      #- name: copy to the server
        #run: rsync firstfile.py ~/tetsss4/rs
        #  run: ssh dev_host 'mkdir ~/tetsss4'