name: Connect ssh
on:
  push:
jobs:
  Name_of_job_can_use_through_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" >  ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          echo "SSH_DEV_HOST" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_DEV_HOST: ${{ secrets.SSH_DEV_HOST }}

      - name: Create dir
        run: ssh SSH_USER@SSH_DEV_HOST mkdir ~/tets