name: Test event
on:
  push:

jobs:
 test_job:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code, Clone repo
       uses: actions/checkout@v3

     - name: Run script
       env:
         VAR: '1234'
       run: |
         sh scripts/print_something.sh

